/*
 * generated by Xtext 2.22.0
 */
package tdt4250.pseudocode.parser.antlr;

import org.antlr.runtime.Token;
import org.antlr.runtime.TokenSource;
import org.eclipse.xtext.parser.antlr.AbstractIndentationTokenSource;
import tdt4250.pseudocode.parser.antlr.internal.InternalPcodeParser;

public class PcodeTokenSource extends AbstractIndentationTokenSource {

	public PcodeTokenSource(TokenSource delegate) {
		super(delegate);
	}

	@Override
	protected boolean shouldSplitTokenImpl(Token token) {
		// TODO Review assumption
		return token.getType() == InternalPcodeParser.RULE_WS;
	}

	@Override
	protected int getBeginTokenType() {
		// TODO Review assumption
		return InternalPcodeParser.RULE_BEGIN;
	}

	@Override
	protected int getEndTokenType() {
		// TODO Review assumption
		return InternalPcodeParser.RULE_END;
	}

}
