/*
 * generated by Xtext 2.22.0
 */
package tdt4250.pseudocode.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class PcodeGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class PseudoClassElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "tdt4250.pseudocode.Pcode.PseudoClass");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cPseudoClassAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cPseudoClassKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cVisibilityKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cVisibilityAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cVisibilityVisibilityKindEnumRuleCall_4_1_0 = (RuleCall)cVisibilityAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cTypeKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cTypeAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final CrossReference cTypePseudoTypeCrossReference_5_1_0 = (CrossReference)cTypeAssignment_5_1.eContents().get(0);
		private final RuleCall cTypePseudoTypeEStringParserRuleCall_5_1_0_1 = (RuleCall)cTypePseudoTypeCrossReference_5_1_0.eContents().get(1);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cSuperTypesKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cSuperTypesAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final CrossReference cSuperTypesPseudoTypeCrossReference_6_2_0 = (CrossReference)cSuperTypesAssignment_6_2.eContents().get(0);
		private final RuleCall cSuperTypesPseudoTypeEStringParserRuleCall_6_2_0_1 = (RuleCall)cSuperTypesPseudoTypeCrossReference_6_2_0.eContents().get(1);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cSuperTypesAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final CrossReference cSuperTypesPseudoTypeCrossReference_6_3_1_0 = (CrossReference)cSuperTypesAssignment_6_3_1.eContents().get(0);
		private final RuleCall cSuperTypesPseudoTypeEStringParserRuleCall_6_3_1_0_1 = (RuleCall)cSuperTypesPseudoTypeCrossReference_6_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cMembersKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cMembersAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cMembersMemberParserRuleCall_7_2_0 = (RuleCall)cMembersAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cMembersAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cMembersMemberParserRuleCall_7_3_1_0 = (RuleCall)cMembersAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//PseudoClass:
		//	{PseudoClass}
		//	'PseudoClass'
		//	name=EString
		//	'{' ('visibility' visibility=VisibilityKind)? ('type' type=[PseudoType|EString])? ('superTypes' '('
		//	superTypes+=[PseudoType|EString] ("," superTypes+=[PseudoType|EString])* ')')? ('members' '{' members+=Member (","
		//	members+=Member)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{PseudoClass} 'PseudoClass' name=EString '{' ('visibility' visibility=VisibilityKind)? ('type'
		//type=[PseudoType|EString])? ('superTypes' '(' superTypes+=[PseudoType|EString] ("," superTypes+=[PseudoType|EString])*
		//')')? ('members' '{' members+=Member ("," members+=Member)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//{PseudoClass}
		public Action getPseudoClassAction_0() { return cPseudoClassAction_0; }
		
		//'PseudoClass'
		public Keyword getPseudoClassKeyword_1() { return cPseudoClassKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('visibility' visibility=VisibilityKind)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'visibility'
		public Keyword getVisibilityKeyword_4_0() { return cVisibilityKeyword_4_0; }
		
		//visibility=VisibilityKind
		public Assignment getVisibilityAssignment_4_1() { return cVisibilityAssignment_4_1; }
		
		//VisibilityKind
		public RuleCall getVisibilityVisibilityKindEnumRuleCall_4_1_0() { return cVisibilityVisibilityKindEnumRuleCall_4_1_0; }
		
		//('type' type=[PseudoType|EString])?
		public Group getGroup_5() { return cGroup_5; }
		
		//'type'
		public Keyword getTypeKeyword_5_0() { return cTypeKeyword_5_0; }
		
		//type=[PseudoType|EString]
		public Assignment getTypeAssignment_5_1() { return cTypeAssignment_5_1; }
		
		//[PseudoType|EString]
		public CrossReference getTypePseudoTypeCrossReference_5_1_0() { return cTypePseudoTypeCrossReference_5_1_0; }
		
		//EString
		public RuleCall getTypePseudoTypeEStringParserRuleCall_5_1_0_1() { return cTypePseudoTypeEStringParserRuleCall_5_1_0_1; }
		
		//('superTypes' '(' superTypes+=[PseudoType|EString] ("," superTypes+=[PseudoType|EString])* ')')?
		public Group getGroup_6() { return cGroup_6; }
		
		//'superTypes'
		public Keyword getSuperTypesKeyword_6_0() { return cSuperTypesKeyword_6_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_6_1() { return cLeftParenthesisKeyword_6_1; }
		
		//superTypes+=[PseudoType|EString]
		public Assignment getSuperTypesAssignment_6_2() { return cSuperTypesAssignment_6_2; }
		
		//[PseudoType|EString]
		public CrossReference getSuperTypesPseudoTypeCrossReference_6_2_0() { return cSuperTypesPseudoTypeCrossReference_6_2_0; }
		
		//EString
		public RuleCall getSuperTypesPseudoTypeEStringParserRuleCall_6_2_0_1() { return cSuperTypesPseudoTypeEStringParserRuleCall_6_2_0_1; }
		
		//("," superTypes+=[PseudoType|EString])*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//superTypes+=[PseudoType|EString]
		public Assignment getSuperTypesAssignment_6_3_1() { return cSuperTypesAssignment_6_3_1; }
		
		//[PseudoType|EString]
		public CrossReference getSuperTypesPseudoTypeCrossReference_6_3_1_0() { return cSuperTypesPseudoTypeCrossReference_6_3_1_0; }
		
		//EString
		public RuleCall getSuperTypesPseudoTypeEStringParserRuleCall_6_3_1_0_1() { return cSuperTypesPseudoTypeEStringParserRuleCall_6_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_6_4() { return cRightParenthesisKeyword_6_4; }
		
		//('members' '{' members+=Member ("," members+=Member)* '}')?
		public Group getGroup_7() { return cGroup_7; }
		
		//'members'
		public Keyword getMembersKeyword_7_0() { return cMembersKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//members+=Member
		public Assignment getMembersAssignment_7_2() { return cMembersAssignment_7_2; }
		
		//Member
		public RuleCall getMembersMemberParserRuleCall_7_2_0() { return cMembersMemberParserRuleCall_7_2_0; }
		
		//("," members+=Member)*
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }
		
		//members+=Member
		public Assignment getMembersAssignment_7_3_1() { return cMembersAssignment_7_3_1; }
		
		//Member
		public RuleCall getMembersMemberParserRuleCall_7_3_1_0() { return cMembersMemberParserRuleCall_7_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class PseudoTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "tdt4250.pseudocode.Pcode.PseudoType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cPseudoClassParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cPseudoInterfaceParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//PseudoType:
		//	PseudoClass | PseudoInterface;
		@Override public ParserRule getRule() { return rule; }
		
		//PseudoClass | PseudoInterface
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//PseudoClass
		public RuleCall getPseudoClassParserRuleCall_0() { return cPseudoClassParserRuleCall_0; }
		
		//PseudoInterface
		public RuleCall getPseudoInterfaceParserRuleCall_1() { return cPseudoInterfaceParserRuleCall_1; }
	}
	public class MemberElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "tdt4250.pseudocode.Pcode.Member");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cMember_ImplParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cPseudoClassParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cPseudoInterfaceParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cFieldParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cOperation_ImplParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cMethodParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cConstructorParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		
		//Member:
		//	Member_Impl | PseudoClass | PseudoInterface | Field | Operation_Impl | Method | Constructor;
		@Override public ParserRule getRule() { return rule; }
		
		//Member_Impl | PseudoClass | PseudoInterface | Field | Operation_Impl | Method | Constructor
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Member_Impl
		public RuleCall getMember_ImplParserRuleCall_0() { return cMember_ImplParserRuleCall_0; }
		
		//PseudoClass
		public RuleCall getPseudoClassParserRuleCall_1() { return cPseudoClassParserRuleCall_1; }
		
		//PseudoInterface
		public RuleCall getPseudoInterfaceParserRuleCall_2() { return cPseudoInterfaceParserRuleCall_2; }
		
		//Field
		public RuleCall getFieldParserRuleCall_3() { return cFieldParserRuleCall_3; }
		
		//Operation_Impl
		public RuleCall getOperation_ImplParserRuleCall_4() { return cOperation_ImplParserRuleCall_4; }
		
		//Method
		public RuleCall getMethodParserRuleCall_5() { return cMethodParserRuleCall_5; }
		
		//Constructor
		public RuleCall getConstructorParserRuleCall_6() { return cConstructorParserRuleCall_6; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "tdt4250.pseudocode.Pcode.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class Member_ImplElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "tdt4250.pseudocode.Pcode.Member_Impl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMemberAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cMemberKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cVisibilityKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cVisibilityAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cVisibilityVisibilityKindEnumRuleCall_4_1_0 = (RuleCall)cVisibilityAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cTypeKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cTypeAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final CrossReference cTypePseudoTypeCrossReference_5_1_0 = (CrossReference)cTypeAssignment_5_1.eContents().get(0);
		private final RuleCall cTypePseudoTypeEStringParserRuleCall_5_1_0_1 = (RuleCall)cTypePseudoTypeCrossReference_5_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Member_Impl Member:
		//	{Member}
		//	'Member'
		//	name=EString
		//	'{' ('visibility' visibility=VisibilityKind)? ('type' type=[PseudoType|EString])?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Member} 'Member' name=EString '{' ('visibility' visibility=VisibilityKind)? ('type' type=[PseudoType|EString])? '}'
		public Group getGroup() { return cGroup; }
		
		//{Member}
		public Action getMemberAction_0() { return cMemberAction_0; }
		
		//'Member'
		public Keyword getMemberKeyword_1() { return cMemberKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('visibility' visibility=VisibilityKind)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'visibility'
		public Keyword getVisibilityKeyword_4_0() { return cVisibilityKeyword_4_0; }
		
		//visibility=VisibilityKind
		public Assignment getVisibilityAssignment_4_1() { return cVisibilityAssignment_4_1; }
		
		//VisibilityKind
		public RuleCall getVisibilityVisibilityKindEnumRuleCall_4_1_0() { return cVisibilityVisibilityKindEnumRuleCall_4_1_0; }
		
		//('type' type=[PseudoType|EString])?
		public Group getGroup_5() { return cGroup_5; }
		
		//'type'
		public Keyword getTypeKeyword_5_0() { return cTypeKeyword_5_0; }
		
		//type=[PseudoType|EString]
		public Assignment getTypeAssignment_5_1() { return cTypeAssignment_5_1; }
		
		//[PseudoType|EString]
		public CrossReference getTypePseudoTypeCrossReference_5_1_0() { return cTypePseudoTypeCrossReference_5_1_0; }
		
		//EString
		public RuleCall getTypePseudoTypeEStringParserRuleCall_5_1_0_1() { return cTypePseudoTypeEStringParserRuleCall_5_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class PseudoInterfaceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "tdt4250.pseudocode.Pcode.PseudoInterface");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cPseudoInterfaceAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cPseudoInterfaceKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cVisibilityKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cVisibilityAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cVisibilityVisibilityKindEnumRuleCall_4_1_0 = (RuleCall)cVisibilityAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cTypeKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cTypeAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final CrossReference cTypePseudoTypeCrossReference_5_1_0 = (CrossReference)cTypeAssignment_5_1.eContents().get(0);
		private final RuleCall cTypePseudoTypeEStringParserRuleCall_5_1_0_1 = (RuleCall)cTypePseudoTypeCrossReference_5_1_0.eContents().get(1);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cSuperTypesKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cSuperTypesAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final CrossReference cSuperTypesPseudoTypeCrossReference_6_2_0 = (CrossReference)cSuperTypesAssignment_6_2.eContents().get(0);
		private final RuleCall cSuperTypesPseudoTypeEStringParserRuleCall_6_2_0_1 = (RuleCall)cSuperTypesPseudoTypeCrossReference_6_2_0.eContents().get(1);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cSuperTypesAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final CrossReference cSuperTypesPseudoTypeCrossReference_6_3_1_0 = (CrossReference)cSuperTypesAssignment_6_3_1.eContents().get(0);
		private final RuleCall cSuperTypesPseudoTypeEStringParserRuleCall_6_3_1_0_1 = (RuleCall)cSuperTypesPseudoTypeCrossReference_6_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cMembersKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cMembersAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cMembersMemberParserRuleCall_7_2_0 = (RuleCall)cMembersAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cMembersAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cMembersMemberParserRuleCall_7_3_1_0 = (RuleCall)cMembersAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//PseudoInterface:
		//	{PseudoInterface}
		//	'PseudoInterface'
		//	name=EString
		//	'{' ('visibility' visibility=VisibilityKind)? ('type' type=[PseudoType|EString])? ('superTypes' '('
		//	superTypes+=[PseudoType|EString] ("," superTypes+=[PseudoType|EString])* ')')? ('members' '{' members+=Member (","
		//	members+=Member)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{PseudoInterface} 'PseudoInterface' name=EString '{' ('visibility' visibility=VisibilityKind)? ('type'
		//type=[PseudoType|EString])? ('superTypes' '(' superTypes+=[PseudoType|EString] ("," superTypes+=[PseudoType|EString])*
		//')')? ('members' '{' members+=Member ("," members+=Member)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//{PseudoInterface}
		public Action getPseudoInterfaceAction_0() { return cPseudoInterfaceAction_0; }
		
		//'PseudoInterface'
		public Keyword getPseudoInterfaceKeyword_1() { return cPseudoInterfaceKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('visibility' visibility=VisibilityKind)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'visibility'
		public Keyword getVisibilityKeyword_4_0() { return cVisibilityKeyword_4_0; }
		
		//visibility=VisibilityKind
		public Assignment getVisibilityAssignment_4_1() { return cVisibilityAssignment_4_1; }
		
		//VisibilityKind
		public RuleCall getVisibilityVisibilityKindEnumRuleCall_4_1_0() { return cVisibilityVisibilityKindEnumRuleCall_4_1_0; }
		
		//('type' type=[PseudoType|EString])?
		public Group getGroup_5() { return cGroup_5; }
		
		//'type'
		public Keyword getTypeKeyword_5_0() { return cTypeKeyword_5_0; }
		
		//type=[PseudoType|EString]
		public Assignment getTypeAssignment_5_1() { return cTypeAssignment_5_1; }
		
		//[PseudoType|EString]
		public CrossReference getTypePseudoTypeCrossReference_5_1_0() { return cTypePseudoTypeCrossReference_5_1_0; }
		
		//EString
		public RuleCall getTypePseudoTypeEStringParserRuleCall_5_1_0_1() { return cTypePseudoTypeEStringParserRuleCall_5_1_0_1; }
		
		//('superTypes' '(' superTypes+=[PseudoType|EString] ("," superTypes+=[PseudoType|EString])* ')')?
		public Group getGroup_6() { return cGroup_6; }
		
		//'superTypes'
		public Keyword getSuperTypesKeyword_6_0() { return cSuperTypesKeyword_6_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_6_1() { return cLeftParenthesisKeyword_6_1; }
		
		//superTypes+=[PseudoType|EString]
		public Assignment getSuperTypesAssignment_6_2() { return cSuperTypesAssignment_6_2; }
		
		//[PseudoType|EString]
		public CrossReference getSuperTypesPseudoTypeCrossReference_6_2_0() { return cSuperTypesPseudoTypeCrossReference_6_2_0; }
		
		//EString
		public RuleCall getSuperTypesPseudoTypeEStringParserRuleCall_6_2_0_1() { return cSuperTypesPseudoTypeEStringParserRuleCall_6_2_0_1; }
		
		//("," superTypes+=[PseudoType|EString])*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//superTypes+=[PseudoType|EString]
		public Assignment getSuperTypesAssignment_6_3_1() { return cSuperTypesAssignment_6_3_1; }
		
		//[PseudoType|EString]
		public CrossReference getSuperTypesPseudoTypeCrossReference_6_3_1_0() { return cSuperTypesPseudoTypeCrossReference_6_3_1_0; }
		
		//EString
		public RuleCall getSuperTypesPseudoTypeEStringParserRuleCall_6_3_1_0_1() { return cSuperTypesPseudoTypeEStringParserRuleCall_6_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_6_4() { return cRightParenthesisKeyword_6_4; }
		
		//('members' '{' members+=Member ("," members+=Member)* '}')?
		public Group getGroup_7() { return cGroup_7; }
		
		//'members'
		public Keyword getMembersKeyword_7_0() { return cMembersKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//members+=Member
		public Assignment getMembersAssignment_7_2() { return cMembersAssignment_7_2; }
		
		//Member
		public RuleCall getMembersMemberParserRuleCall_7_2_0() { return cMembersMemberParserRuleCall_7_2_0; }
		
		//("," members+=Member)*
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }
		
		//members+=Member
		public Assignment getMembersAssignment_7_3_1() { return cMembersAssignment_7_3_1; }
		
		//Member
		public RuleCall getMembersMemberParserRuleCall_7_3_1_0() { return cMembersMemberParserRuleCall_7_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class FieldElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "tdt4250.pseudocode.Pcode.Field");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFieldAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cFieldKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cVisibilityKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cVisibilityAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cVisibilityVisibilityKindEnumRuleCall_4_1_0 = (RuleCall)cVisibilityAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cTypeKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cTypeAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final CrossReference cTypePseudoTypeCrossReference_5_1_0 = (CrossReference)cTypeAssignment_5_1.eContents().get(0);
		private final RuleCall cTypePseudoTypeEStringParserRuleCall_5_1_0_1 = (RuleCall)cTypePseudoTypeCrossReference_5_1_0.eContents().get(1);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cInitializerKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cInitializerAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final CrossReference cInitializerExpressionCrossReference_6_1_0 = (CrossReference)cInitializerAssignment_6_1.eContents().get(0);
		private final RuleCall cInitializerExpressionEStringParserRuleCall_6_1_0_1 = (RuleCall)cInitializerExpressionCrossReference_6_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Field:
		//	{Field}
		//	'Field'
		//	name=EString
		//	'{' ('visibility' visibility=VisibilityKind)? ('type' type=[PseudoType|EString])? ('initializer'
		//	initializer=[Expression|EString])?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Field} 'Field' name=EString '{' ('visibility' visibility=VisibilityKind)? ('type' type=[PseudoType|EString])?
		//('initializer' initializer=[Expression|EString])? '}'
		public Group getGroup() { return cGroup; }
		
		//{Field}
		public Action getFieldAction_0() { return cFieldAction_0; }
		
		//'Field'
		public Keyword getFieldKeyword_1() { return cFieldKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('visibility' visibility=VisibilityKind)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'visibility'
		public Keyword getVisibilityKeyword_4_0() { return cVisibilityKeyword_4_0; }
		
		//visibility=VisibilityKind
		public Assignment getVisibilityAssignment_4_1() { return cVisibilityAssignment_4_1; }
		
		//VisibilityKind
		public RuleCall getVisibilityVisibilityKindEnumRuleCall_4_1_0() { return cVisibilityVisibilityKindEnumRuleCall_4_1_0; }
		
		//('type' type=[PseudoType|EString])?
		public Group getGroup_5() { return cGroup_5; }
		
		//'type'
		public Keyword getTypeKeyword_5_0() { return cTypeKeyword_5_0; }
		
		//type=[PseudoType|EString]
		public Assignment getTypeAssignment_5_1() { return cTypeAssignment_5_1; }
		
		//[PseudoType|EString]
		public CrossReference getTypePseudoTypeCrossReference_5_1_0() { return cTypePseudoTypeCrossReference_5_1_0; }
		
		//EString
		public RuleCall getTypePseudoTypeEStringParserRuleCall_5_1_0_1() { return cTypePseudoTypeEStringParserRuleCall_5_1_0_1; }
		
		//('initializer' initializer=[Expression|EString])?
		public Group getGroup_6() { return cGroup_6; }
		
		//'initializer'
		public Keyword getInitializerKeyword_6_0() { return cInitializerKeyword_6_0; }
		
		//initializer=[Expression|EString]
		public Assignment getInitializerAssignment_6_1() { return cInitializerAssignment_6_1; }
		
		//[Expression|EString]
		public CrossReference getInitializerExpressionCrossReference_6_1_0() { return cInitializerExpressionCrossReference_6_1_0; }
		
		//EString
		public RuleCall getInitializerExpressionEStringParserRuleCall_6_1_0_1() { return cInitializerExpressionEStringParserRuleCall_6_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class Operation_ImplElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "tdt4250.pseudocode.Pcode.Operation_Impl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cOperationAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cOperationKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cVisibilityKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cVisibilityAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cVisibilityVisibilityKindEnumRuleCall_4_1_0 = (RuleCall)cVisibilityAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cTypeKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cTypeAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final CrossReference cTypePseudoTypeCrossReference_5_1_0 = (CrossReference)cTypeAssignment_5_1.eContents().get(0);
		private final RuleCall cTypePseudoTypeEStringParserRuleCall_5_1_0_1 = (RuleCall)cTypePseudoTypeCrossReference_5_1_0.eContents().get(1);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cExceptionsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cExceptionsAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final CrossReference cExceptionsPseudoTypeCrossReference_6_1_0 = (CrossReference)cExceptionsAssignment_6_1.eContents().get(0);
		private final RuleCall cExceptionsPseudoTypeEStringParserRuleCall_6_1_0_1 = (RuleCall)cExceptionsPseudoTypeCrossReference_6_1_0.eContents().get(1);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cParametersKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cParametersAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cParametersParameterParserRuleCall_7_2_0 = (RuleCall)cParametersAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cParametersAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cParametersParameterParserRuleCall_7_3_1_0 = (RuleCall)cParametersAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Operation_Impl Operation:
		//	{Operation}
		//	'Operation'
		//	name=EString
		//	'{' ('visibility' visibility=VisibilityKind)? ('type' type=[PseudoType|EString])? ('exceptions'
		//	exceptions=[PseudoType|EString])? ('parameters' '{' parameters+=Parameter ("," parameters+=Parameter)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Operation} 'Operation' name=EString '{' ('visibility' visibility=VisibilityKind)? ('type' type=[PseudoType|EString])?
		//('exceptions' exceptions=[PseudoType|EString])? ('parameters' '{' parameters+=Parameter ("," parameters+=Parameter)*
		//'}')? '}'
		public Group getGroup() { return cGroup; }
		
		//{Operation}
		public Action getOperationAction_0() { return cOperationAction_0; }
		
		//'Operation'
		public Keyword getOperationKeyword_1() { return cOperationKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('visibility' visibility=VisibilityKind)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'visibility'
		public Keyword getVisibilityKeyword_4_0() { return cVisibilityKeyword_4_0; }
		
		//visibility=VisibilityKind
		public Assignment getVisibilityAssignment_4_1() { return cVisibilityAssignment_4_1; }
		
		//VisibilityKind
		public RuleCall getVisibilityVisibilityKindEnumRuleCall_4_1_0() { return cVisibilityVisibilityKindEnumRuleCall_4_1_0; }
		
		//('type' type=[PseudoType|EString])?
		public Group getGroup_5() { return cGroup_5; }
		
		//'type'
		public Keyword getTypeKeyword_5_0() { return cTypeKeyword_5_0; }
		
		//type=[PseudoType|EString]
		public Assignment getTypeAssignment_5_1() { return cTypeAssignment_5_1; }
		
		//[PseudoType|EString]
		public CrossReference getTypePseudoTypeCrossReference_5_1_0() { return cTypePseudoTypeCrossReference_5_1_0; }
		
		//EString
		public RuleCall getTypePseudoTypeEStringParserRuleCall_5_1_0_1() { return cTypePseudoTypeEStringParserRuleCall_5_1_0_1; }
		
		//('exceptions' exceptions=[PseudoType|EString])?
		public Group getGroup_6() { return cGroup_6; }
		
		//'exceptions'
		public Keyword getExceptionsKeyword_6_0() { return cExceptionsKeyword_6_0; }
		
		//exceptions=[PseudoType|EString]
		public Assignment getExceptionsAssignment_6_1() { return cExceptionsAssignment_6_1; }
		
		//[PseudoType|EString]
		public CrossReference getExceptionsPseudoTypeCrossReference_6_1_0() { return cExceptionsPseudoTypeCrossReference_6_1_0; }
		
		//EString
		public RuleCall getExceptionsPseudoTypeEStringParserRuleCall_6_1_0_1() { return cExceptionsPseudoTypeEStringParserRuleCall_6_1_0_1; }
		
		//('parameters' '{' parameters+=Parameter ("," parameters+=Parameter)* '}')?
		public Group getGroup_7() { return cGroup_7; }
		
		//'parameters'
		public Keyword getParametersKeyword_7_0() { return cParametersKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//parameters+=Parameter
		public Assignment getParametersAssignment_7_2() { return cParametersAssignment_7_2; }
		
		//Parameter
		public RuleCall getParametersParameterParserRuleCall_7_2_0() { return cParametersParameterParserRuleCall_7_2_0; }
		
		//("," parameters+=Parameter)*
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }
		
		//parameters+=Parameter
		public Assignment getParametersAssignment_7_3_1() { return cParametersAssignment_7_3_1; }
		
		//Parameter
		public RuleCall getParametersParameterParserRuleCall_7_3_1_0() { return cParametersParameterParserRuleCall_7_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class MethodElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "tdt4250.pseudocode.Pcode.Method");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMethodAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cMethodKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cVisibilityKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cVisibilityAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cVisibilityVisibilityKindEnumRuleCall_4_1_0 = (RuleCall)cVisibilityAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cTypeKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cTypeAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final CrossReference cTypePseudoTypeCrossReference_5_1_0 = (CrossReference)cTypeAssignment_5_1.eContents().get(0);
		private final RuleCall cTypePseudoTypeEStringParserRuleCall_5_1_0_1 = (RuleCall)cTypePseudoTypeCrossReference_5_1_0.eContents().get(1);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cExceptionsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cExceptionsAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final CrossReference cExceptionsPseudoTypeCrossReference_6_1_0 = (CrossReference)cExceptionsAssignment_6_1.eContents().get(0);
		private final RuleCall cExceptionsPseudoTypeEStringParserRuleCall_6_1_0_1 = (RuleCall)cExceptionsPseudoTypeCrossReference_6_1_0.eContents().get(1);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cParametersKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cParametersAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cParametersParameterParserRuleCall_7_2_0 = (RuleCall)cParametersAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cParametersAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cParametersParameterParserRuleCall_7_3_1_0 = (RuleCall)cParametersAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Method:
		//	{Method}
		//	'Method'
		//	name=EString
		//	'{' ('visibility' visibility=VisibilityKind)? ('type' type=[PseudoType|EString])? ('exceptions'
		//	exceptions=[PseudoType|EString])? ('parameters' '{' parameters+=Parameter ("," parameters+=Parameter)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Method} 'Method' name=EString '{' ('visibility' visibility=VisibilityKind)? ('type' type=[PseudoType|EString])?
		//('exceptions' exceptions=[PseudoType|EString])? ('parameters' '{' parameters+=Parameter ("," parameters+=Parameter)*
		//'}')? '}'
		public Group getGroup() { return cGroup; }
		
		//{Method}
		public Action getMethodAction_0() { return cMethodAction_0; }
		
		//'Method'
		public Keyword getMethodKeyword_1() { return cMethodKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('visibility' visibility=VisibilityKind)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'visibility'
		public Keyword getVisibilityKeyword_4_0() { return cVisibilityKeyword_4_0; }
		
		//visibility=VisibilityKind
		public Assignment getVisibilityAssignment_4_1() { return cVisibilityAssignment_4_1; }
		
		//VisibilityKind
		public RuleCall getVisibilityVisibilityKindEnumRuleCall_4_1_0() { return cVisibilityVisibilityKindEnumRuleCall_4_1_0; }
		
		//('type' type=[PseudoType|EString])?
		public Group getGroup_5() { return cGroup_5; }
		
		//'type'
		public Keyword getTypeKeyword_5_0() { return cTypeKeyword_5_0; }
		
		//type=[PseudoType|EString]
		public Assignment getTypeAssignment_5_1() { return cTypeAssignment_5_1; }
		
		//[PseudoType|EString]
		public CrossReference getTypePseudoTypeCrossReference_5_1_0() { return cTypePseudoTypeCrossReference_5_1_0; }
		
		//EString
		public RuleCall getTypePseudoTypeEStringParserRuleCall_5_1_0_1() { return cTypePseudoTypeEStringParserRuleCall_5_1_0_1; }
		
		//('exceptions' exceptions=[PseudoType|EString])?
		public Group getGroup_6() { return cGroup_6; }
		
		//'exceptions'
		public Keyword getExceptionsKeyword_6_0() { return cExceptionsKeyword_6_0; }
		
		//exceptions=[PseudoType|EString]
		public Assignment getExceptionsAssignment_6_1() { return cExceptionsAssignment_6_1; }
		
		//[PseudoType|EString]
		public CrossReference getExceptionsPseudoTypeCrossReference_6_1_0() { return cExceptionsPseudoTypeCrossReference_6_1_0; }
		
		//EString
		public RuleCall getExceptionsPseudoTypeEStringParserRuleCall_6_1_0_1() { return cExceptionsPseudoTypeEStringParserRuleCall_6_1_0_1; }
		
		//('parameters' '{' parameters+=Parameter ("," parameters+=Parameter)* '}')?
		public Group getGroup_7() { return cGroup_7; }
		
		//'parameters'
		public Keyword getParametersKeyword_7_0() { return cParametersKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//parameters+=Parameter
		public Assignment getParametersAssignment_7_2() { return cParametersAssignment_7_2; }
		
		//Parameter
		public RuleCall getParametersParameterParserRuleCall_7_2_0() { return cParametersParameterParserRuleCall_7_2_0; }
		
		//("," parameters+=Parameter)*
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }
		
		//parameters+=Parameter
		public Assignment getParametersAssignment_7_3_1() { return cParametersAssignment_7_3_1; }
		
		//Parameter
		public RuleCall getParametersParameterParserRuleCall_7_3_1_0() { return cParametersParameterParserRuleCall_7_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class ConstructorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "tdt4250.pseudocode.Pcode.Constructor");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cConstructorAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cConstructorKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cVisibilityKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cVisibilityAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cVisibilityVisibilityKindEnumRuleCall_4_1_0 = (RuleCall)cVisibilityAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cTypeKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cTypeAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final CrossReference cTypePseudoTypeCrossReference_5_1_0 = (CrossReference)cTypeAssignment_5_1.eContents().get(0);
		private final RuleCall cTypePseudoTypeEStringParserRuleCall_5_1_0_1 = (RuleCall)cTypePseudoTypeCrossReference_5_1_0.eContents().get(1);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cExceptionsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cExceptionsAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final CrossReference cExceptionsPseudoTypeCrossReference_6_1_0 = (CrossReference)cExceptionsAssignment_6_1.eContents().get(0);
		private final RuleCall cExceptionsPseudoTypeEStringParserRuleCall_6_1_0_1 = (RuleCall)cExceptionsPseudoTypeCrossReference_6_1_0.eContents().get(1);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cParametersKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cParametersAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cParametersParameterParserRuleCall_7_2_0 = (RuleCall)cParametersAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cParametersAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cParametersParameterParserRuleCall_7_3_1_0 = (RuleCall)cParametersAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Constructor:
		//	{Constructor}
		//	'Constructor'
		//	name=EString
		//	'{' ('visibility' visibility=VisibilityKind)? ('type' type=[PseudoType|EString])? ('exceptions'
		//	exceptions=[PseudoType|EString])? ('parameters' '{' parameters+=Parameter ("," parameters+=Parameter)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Constructor} 'Constructor' name=EString '{' ('visibility' visibility=VisibilityKind)? ('type'
		//type=[PseudoType|EString])? ('exceptions' exceptions=[PseudoType|EString])? ('parameters' '{' parameters+=Parameter
		//("," parameters+=Parameter)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//{Constructor}
		public Action getConstructorAction_0() { return cConstructorAction_0; }
		
		//'Constructor'
		public Keyword getConstructorKeyword_1() { return cConstructorKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('visibility' visibility=VisibilityKind)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'visibility'
		public Keyword getVisibilityKeyword_4_0() { return cVisibilityKeyword_4_0; }
		
		//visibility=VisibilityKind
		public Assignment getVisibilityAssignment_4_1() { return cVisibilityAssignment_4_1; }
		
		//VisibilityKind
		public RuleCall getVisibilityVisibilityKindEnumRuleCall_4_1_0() { return cVisibilityVisibilityKindEnumRuleCall_4_1_0; }
		
		//('type' type=[PseudoType|EString])?
		public Group getGroup_5() { return cGroup_5; }
		
		//'type'
		public Keyword getTypeKeyword_5_0() { return cTypeKeyword_5_0; }
		
		//type=[PseudoType|EString]
		public Assignment getTypeAssignment_5_1() { return cTypeAssignment_5_1; }
		
		//[PseudoType|EString]
		public CrossReference getTypePseudoTypeCrossReference_5_1_0() { return cTypePseudoTypeCrossReference_5_1_0; }
		
		//EString
		public RuleCall getTypePseudoTypeEStringParserRuleCall_5_1_0_1() { return cTypePseudoTypeEStringParserRuleCall_5_1_0_1; }
		
		//('exceptions' exceptions=[PseudoType|EString])?
		public Group getGroup_6() { return cGroup_6; }
		
		//'exceptions'
		public Keyword getExceptionsKeyword_6_0() { return cExceptionsKeyword_6_0; }
		
		//exceptions=[PseudoType|EString]
		public Assignment getExceptionsAssignment_6_1() { return cExceptionsAssignment_6_1; }
		
		//[PseudoType|EString]
		public CrossReference getExceptionsPseudoTypeCrossReference_6_1_0() { return cExceptionsPseudoTypeCrossReference_6_1_0; }
		
		//EString
		public RuleCall getExceptionsPseudoTypeEStringParserRuleCall_6_1_0_1() { return cExceptionsPseudoTypeEStringParserRuleCall_6_1_0_1; }
		
		//('parameters' '{' parameters+=Parameter ("," parameters+=Parameter)* '}')?
		public Group getGroup_7() { return cGroup_7; }
		
		//'parameters'
		public Keyword getParametersKeyword_7_0() { return cParametersKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//parameters+=Parameter
		public Assignment getParametersAssignment_7_2() { return cParametersAssignment_7_2; }
		
		//Parameter
		public RuleCall getParametersParameterParserRuleCall_7_2_0() { return cParametersParameterParserRuleCall_7_2_0; }
		
		//("," parameters+=Parameter)*
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }
		
		//parameters+=Parameter
		public Assignment getParametersAssignment_7_3_1() { return cParametersAssignment_7_3_1; }
		
		//Parameter
		public RuleCall getParametersParameterParserRuleCall_7_3_1_0() { return cParametersParameterParserRuleCall_7_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class ExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "tdt4250.pseudocode.Pcode.Expression");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cExpressionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cExpressionKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//Expression:
		//	{Expression}
		//	'Expression';
		@Override public ParserRule getRule() { return rule; }
		
		//{Expression} 'Expression'
		public Group getGroup() { return cGroup; }
		
		//{Expression}
		public Action getExpressionAction_0() { return cExpressionAction_0; }
		
		//'Expression'
		public Keyword getExpressionKeyword_1() { return cExpressionKeyword_1; }
	}
	public class ParameterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "tdt4250.pseudocode.Pcode.Parameter");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cParameterAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cParameterKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTypeKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cTypeAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cTypePseudoTypeCrossReference_4_1_0 = (CrossReference)cTypeAssignment_4_1.eContents().get(0);
		private final RuleCall cTypePseudoTypeEStringParserRuleCall_4_1_0_1 = (RuleCall)cTypePseudoTypeCrossReference_4_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Parameter:
		//	{Parameter}
		//	'Parameter'
		//	name=EString
		//	'{' ('type' type=[PseudoType|EString])?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Parameter} 'Parameter' name=EString '{' ('type' type=[PseudoType|EString])? '}'
		public Group getGroup() { return cGroup; }
		
		//{Parameter}
		public Action getParameterAction_0() { return cParameterAction_0; }
		
		//'Parameter'
		public Keyword getParameterKeyword_1() { return cParameterKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('type' type=[PseudoType|EString])?
		public Group getGroup_4() { return cGroup_4; }
		
		//'type'
		public Keyword getTypeKeyword_4_0() { return cTypeKeyword_4_0; }
		
		//type=[PseudoType|EString]
		public Assignment getTypeAssignment_4_1() { return cTypeAssignment_4_1; }
		
		//[PseudoType|EString]
		public CrossReference getTypePseudoTypeCrossReference_4_1_0() { return cTypePseudoTypeCrossReference_4_1_0; }
		
		//EString
		public RuleCall getTypePseudoTypeEStringParserRuleCall_4_1_0_1() { return cTypePseudoTypeEStringParserRuleCall_4_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	
	public class VisibilityKindElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "tdt4250.pseudocode.Pcode.VisibilityKind");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cPackagePrivateEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cPackagePrivatePackagePrivateKeyword_0_0 = (Keyword)cPackagePrivateEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cPrivateEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cPrivatePrivateKeyword_1_0 = (Keyword)cPrivateEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cProtectedEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cProtectedProtectedKeyword_2_0 = (Keyword)cProtectedEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cPublicEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cPublicPublicKeyword_3_0 = (Keyword)cPublicEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum VisibilityKind:
		//	packagePrivate | private | protected | public;
		public EnumRule getRule() { return rule; }
		
		//packagePrivate | private | protected | public
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//packagePrivate
		public EnumLiteralDeclaration getPackagePrivateEnumLiteralDeclaration_0() { return cPackagePrivateEnumLiteralDeclaration_0; }
		
		//'packagePrivate'
		public Keyword getPackagePrivatePackagePrivateKeyword_0_0() { return cPackagePrivatePackagePrivateKeyword_0_0; }
		
		//private
		public EnumLiteralDeclaration getPrivateEnumLiteralDeclaration_1() { return cPrivateEnumLiteralDeclaration_1; }
		
		//'private'
		public Keyword getPrivatePrivateKeyword_1_0() { return cPrivatePrivateKeyword_1_0; }
		
		//protected
		public EnumLiteralDeclaration getProtectedEnumLiteralDeclaration_2() { return cProtectedEnumLiteralDeclaration_2; }
		
		//'protected'
		public Keyword getProtectedProtectedKeyword_2_0() { return cProtectedProtectedKeyword_2_0; }
		
		//public
		public EnumLiteralDeclaration getPublicEnumLiteralDeclaration_3() { return cPublicEnumLiteralDeclaration_3; }
		
		//'public'
		public Keyword getPublicPublicKeyword_3_0() { return cPublicPublicKeyword_3_0; }
	}
	
	private final PseudoClassElements pPseudoClass;
	private final PseudoTypeElements pPseudoType;
	private final MemberElements pMember;
	private final VisibilityKindElements eVisibilityKind;
	private final EStringElements pEString;
	private final Member_ImplElements pMember_Impl;
	private final PseudoInterfaceElements pPseudoInterface;
	private final FieldElements pField;
	private final Operation_ImplElements pOperation_Impl;
	private final MethodElements pMethod;
	private final ConstructorElements pConstructor;
	private final ExpressionElements pExpression;
	private final ParameterElements pParameter;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public PcodeGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pPseudoClass = new PseudoClassElements();
		this.pPseudoType = new PseudoTypeElements();
		this.pMember = new MemberElements();
		this.eVisibilityKind = new VisibilityKindElements();
		this.pEString = new EStringElements();
		this.pMember_Impl = new Member_ImplElements();
		this.pPseudoInterface = new PseudoInterfaceElements();
		this.pField = new FieldElements();
		this.pOperation_Impl = new Operation_ImplElements();
		this.pMethod = new MethodElements();
		this.pConstructor = new ConstructorElements();
		this.pExpression = new ExpressionElements();
		this.pParameter = new ParameterElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("tdt4250.pseudocode.Pcode".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//PseudoClass:
	//	{PseudoClass}
	//	'PseudoClass'
	//	name=EString
	//	'{' ('visibility' visibility=VisibilityKind)? ('type' type=[PseudoType|EString])? ('superTypes' '('
	//	superTypes+=[PseudoType|EString] ("," superTypes+=[PseudoType|EString])* ')')? ('members' '{' members+=Member (","
	//	members+=Member)* '}')?
	//	'}';
	public PseudoClassElements getPseudoClassAccess() {
		return pPseudoClass;
	}
	
	public ParserRule getPseudoClassRule() {
		return getPseudoClassAccess().getRule();
	}
	
	//PseudoType:
	//	PseudoClass | PseudoInterface;
	public PseudoTypeElements getPseudoTypeAccess() {
		return pPseudoType;
	}
	
	public ParserRule getPseudoTypeRule() {
		return getPseudoTypeAccess().getRule();
	}
	
	//Member:
	//	Member_Impl | PseudoClass | PseudoInterface | Field | Operation_Impl | Method | Constructor;
	public MemberElements getMemberAccess() {
		return pMember;
	}
	
	public ParserRule getMemberRule() {
		return getMemberAccess().getRule();
	}
	
	//enum VisibilityKind:
	//	packagePrivate | private | protected | public;
	public VisibilityKindElements getVisibilityKindAccess() {
		return eVisibilityKind;
	}
	
	public EnumRule getVisibilityKindRule() {
		return getVisibilityKindAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Member_Impl Member:
	//	{Member}
	//	'Member'
	//	name=EString
	//	'{' ('visibility' visibility=VisibilityKind)? ('type' type=[PseudoType|EString])?
	//	'}';
	public Member_ImplElements getMember_ImplAccess() {
		return pMember_Impl;
	}
	
	public ParserRule getMember_ImplRule() {
		return getMember_ImplAccess().getRule();
	}
	
	//PseudoInterface:
	//	{PseudoInterface}
	//	'PseudoInterface'
	//	name=EString
	//	'{' ('visibility' visibility=VisibilityKind)? ('type' type=[PseudoType|EString])? ('superTypes' '('
	//	superTypes+=[PseudoType|EString] ("," superTypes+=[PseudoType|EString])* ')')? ('members' '{' members+=Member (","
	//	members+=Member)* '}')?
	//	'}';
	public PseudoInterfaceElements getPseudoInterfaceAccess() {
		return pPseudoInterface;
	}
	
	public ParserRule getPseudoInterfaceRule() {
		return getPseudoInterfaceAccess().getRule();
	}
	
	//Field:
	//	{Field}
	//	'Field'
	//	name=EString
	//	'{' ('visibility' visibility=VisibilityKind)? ('type' type=[PseudoType|EString])? ('initializer'
	//	initializer=[Expression|EString])?
	//	'}';
	public FieldElements getFieldAccess() {
		return pField;
	}
	
	public ParserRule getFieldRule() {
		return getFieldAccess().getRule();
	}
	
	//Operation_Impl Operation:
	//	{Operation}
	//	'Operation'
	//	name=EString
	//	'{' ('visibility' visibility=VisibilityKind)? ('type' type=[PseudoType|EString])? ('exceptions'
	//	exceptions=[PseudoType|EString])? ('parameters' '{' parameters+=Parameter ("," parameters+=Parameter)* '}')?
	//	'}';
	public Operation_ImplElements getOperation_ImplAccess() {
		return pOperation_Impl;
	}
	
	public ParserRule getOperation_ImplRule() {
		return getOperation_ImplAccess().getRule();
	}
	
	//Method:
	//	{Method}
	//	'Method'
	//	name=EString
	//	'{' ('visibility' visibility=VisibilityKind)? ('type' type=[PseudoType|EString])? ('exceptions'
	//	exceptions=[PseudoType|EString])? ('parameters' '{' parameters+=Parameter ("," parameters+=Parameter)* '}')?
	//	'}';
	public MethodElements getMethodAccess() {
		return pMethod;
	}
	
	public ParserRule getMethodRule() {
		return getMethodAccess().getRule();
	}
	
	//Constructor:
	//	{Constructor}
	//	'Constructor'
	//	name=EString
	//	'{' ('visibility' visibility=VisibilityKind)? ('type' type=[PseudoType|EString])? ('exceptions'
	//	exceptions=[PseudoType|EString])? ('parameters' '{' parameters+=Parameter ("," parameters+=Parameter)* '}')?
	//	'}';
	public ConstructorElements getConstructorAccess() {
		return pConstructor;
	}
	
	public ParserRule getConstructorRule() {
		return getConstructorAccess().getRule();
	}
	
	//Expression:
	//	{Expression}
	//	'Expression';
	public ExpressionElements getExpressionAccess() {
		return pExpression;
	}
	
	public ParserRule getExpressionRule() {
		return getExpressionAccess().getRule();
	}
	
	//Parameter:
	//	{Parameter}
	//	'Parameter'
	//	name=EString
	//	'{' ('type' type=[PseudoType|EString])?
	//	'}';
	public ParameterElements getParameterAccess() {
		return pParameter;
	}
	
	public ParserRule getParameterRule() {
		return getParameterAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
