/*
 * generated by Xtext 2.22.0
 */
package tdt4250.pseudocode.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import tdt4250.pseudocode.xtext.ui.internal.XtextActivator;

public class PcodeUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("tdt4250.pseudocode.Pcode");
	}

}
