/*
 * generated by Xtext 2.23.0
 */
package tdt4250.pseudocode.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import tdt4250.pseudocode.Body;
import tdt4250.pseudocode.Constructor;
import tdt4250.pseudocode.Expression;
import tdt4250.pseudocode.For;
import tdt4250.pseudocode.If;
import tdt4250.pseudocode.Method;
import tdt4250.pseudocode.PseudoClass;
import tdt4250.pseudocode.PseudocodePackage;
import tdt4250.pseudocode.Stop;
import tdt4250.pseudocode.Variable;
import tdt4250.pseudocode.While;
import tdt4250.pseudocode.services.PcodeGrammarAccess;

@SuppressWarnings("all")
public class PcodeSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private PcodeGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == PseudocodePackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case PseudocodePackage.BODY:
				sequence_Body(context, (Body) semanticObject); 
				return; 
			case PseudocodePackage.CONSTRUCTOR:
				sequence_Constructor(context, (Constructor) semanticObject); 
				return; 
			case PseudocodePackage.EXPRESSION:
				sequence_Expression(context, (Expression) semanticObject); 
				return; 
			case PseudocodePackage.FOR:
				sequence_For(context, (For) semanticObject); 
				return; 
			case PseudocodePackage.IF:
				sequence_If(context, (If) semanticObject); 
				return; 
			case PseudocodePackage.METHOD:
				sequence_Method(context, (Method) semanticObject); 
				return; 
			case PseudocodePackage.PARAMETER:
				sequence_Parameter(context, (tdt4250.pseudocode.Parameter) semanticObject); 
				return; 
			case PseudocodePackage.PSEUDO_CLASS:
				sequence_PseudoClass(context, (PseudoClass) semanticObject); 
				return; 
			case PseudocodePackage.STOP:
				sequence_Stop(context, (Stop) semanticObject); 
				return; 
			case PseudocodePackage.VARIABLE:
				sequence_Variable(context, (Variable) semanticObject); 
				return; 
			case PseudocodePackage.WHILE:
				sequence_While(context, (While) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Body returns Body
	 *
	 * Constraint:
	 *     ((statements+=Variable | statements+=If | statements+=For | statements+=While | statements+=Stop)* statements+=Stop)
	 */
	protected void sequence_Body(ISerializationContext context, Body semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Member returns Constructor
	 *     Constructor returns Constructor
	 *
	 * Constraint:
	 *     (name='(' (parameters+=Parameter parameters+=Parameter*)*)
	 */
	protected void sequence_Constructor(ISerializationContext context, Constructor semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Expression returns Expression
	 *
	 * Constraint:
	 *     {Expression}
	 */
	protected void sequence_Expression(ISerializationContext context, Expression semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     For returns For
	 *
	 * Constraint:
	 *     {For}
	 */
	protected void sequence_For(ISerializationContext context, For semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     If returns If
	 *
	 * Constraint:
	 *     {If}
	 */
	protected void sequence_If(ISerializationContext context, If semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Member returns Method
	 *     Method returns Method
	 *
	 * Constraint:
	 *     (name=EString (parameters+=Parameter parameters+=Parameter*)* body=Body)
	 */
	protected void sequence_Method(ISerializationContext context, Method semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Parameter returns Parameter
	 *
	 * Constraint:
	 *     name=EString
	 */
	protected void sequence_Parameter(ISerializationContext context, tdt4250.pseudocode.Parameter semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, PseudocodePackage.Literals.PARAMETER__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, PseudocodePackage.Literals.PARAMETER__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getParameterAccess().getNameEStringParserRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     PseudoClass returns PseudoClass
	 *     Member returns PseudoClass
	 *
	 * Constraint:
	 *     (name=EString members+=Constructor* members+=Method*)
	 */
	protected void sequence_PseudoClass(ISerializationContext context, PseudoClass semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Stop returns Stop
	 *
	 * Constraint:
	 *     {Stop}
	 */
	protected void sequence_Stop(ISerializationContext context, Stop semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Variable returns Variable
	 *
	 * Constraint:
	 *     expressions+=Expression
	 */
	protected void sequence_Variable(ISerializationContext context, Variable semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     While returns While
	 *
	 * Constraint:
	 *     {While}
	 */
	protected void sequence_While(ISerializationContext context, While semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
