/*
 * generated by Xtext 2.22.0
 */
package tdt4250.mush.xtext;

import org.eclipse.emf.ecore.EPackage;

import com.google.inject.Injector;

import tdt4250.mush.model.MushPackage;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MushStandaloneSetup extends MushStandaloneSetupGenerated {

	public static void doSetup() {
		new MushStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
	
	@Override
	public void register(Injector injector) {
		super.register(injector);
		EPackage.Registry.INSTANCE.put(MushPackage.eNS_URI, MushPackage.eINSTANCE);
	}
}
