/*
 * generated by Xtext 2.22.0
 */
package tdt4250.mush.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMushScopeProvider extends DelegatingScopeProvider {
}
