/**
 * generated by Xtext 2.22.0
 */
package tdt4250.pseudocode.pseudocode.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import tdt4250.pseudocode.pseudocode.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class PseudocodeFactoryImpl extends EFactoryImpl implements PseudocodeFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static PseudocodeFactory init()
  {
    try
    {
      PseudocodeFactory thePseudocodeFactory = (PseudocodeFactory)EPackage.Registry.INSTANCE.getEFactory(PseudocodePackage.eNS_URI);
      if (thePseudocodeFactory != null)
      {
        return thePseudocodeFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new PseudocodeFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PseudocodeFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case PseudocodePackage.SIZE_EXPRESSION: return createSizeExpression();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SizeExpression createSizeExpression()
  {
    SizeExpressionImpl sizeExpression = new SizeExpressionImpl();
    return sizeExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PseudocodePackage getPseudocodePackage()
  {
    return (PseudocodePackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static PseudocodePackage getPackage()
  {
    return PseudocodePackage.eINSTANCE;
  }

} //PseudocodeFactoryImpl
