/**
 * generated by Xtext 2.22.0
 */
package tdt4250.pseudocode.tests;

import com.google.inject.Inject;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.util.EmfFormatter;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.eclipse.xtext.xbase.lib.InputOutput;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import tdt4250.pseudocode.Model;
import tdt4250.pseudocode.tests.PcodeInjectorProvider;

@ExtendWith(InjectionExtension.class)
@InjectWith(PcodeInjectorProvider.class)
@SuppressWarnings("all")
public class PcodeParsingTest {
  @Inject
  private ParseHelper<Model> parseHelper;
  
  @Test
  public void loadModel() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("ANNABELLE(alder,hoyde)");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("G = [[1,1],[2,2]]");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("i = 0");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("j = 1");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("if i==0 then");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("exchange G at 1,1 with G[i][j]");
      _builder.newLine();
      final Model result = this.parseHelper.parse(_builder);
      InputOutput.<String>println(EmfFormatter.objToStr(result));
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      boolean _isEmpty = errors.isEmpty();
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("Unexpected errors: ");
      String _join = IterableExtensions.join(errors, ", ");
      _builder_1.append(_join);
      Assertions.assertTrue(_isEmpty, _builder_1.toString());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
